/**
* This is an autogenerated file created by the Stencil compiler.
* It contains typing information for all components that exist in this project.
*/
/* tslint:disable */

import '@stencil/core';

import '@ionic/core';
import 'ionicons';
import '@plastic/chat';
import '@plastic/d3-stencil';


export namespace Components {

  interface SiteRoot {}
  interface SiteRootAttributes extends StencilHTMLAttributes {}

  interface HomePage {}
  interface HomePageAttributes extends StencilHTMLAttributes {}

  interface SettingsPage {}
  interface SettingsPageAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'SiteRoot': Components.SiteRoot;
    'HomePage': Components.HomePage;
    'SettingsPage': Components.SettingsPage;
  }

  interface StencilIntrinsicElements {
    'site-root': Components.SiteRootAttributes;
    'home-page': Components.HomePageAttributes;
    'settings-page': Components.SettingsPageAttributes;
  }


  interface HTMLSiteRootElement extends Components.SiteRoot, HTMLStencilElement {}
  var HTMLSiteRootElement: {
    prototype: HTMLSiteRootElement;
    new (): HTMLSiteRootElement;
  };

  interface HTMLHomePageElement extends Components.HomePage, HTMLStencilElement {}
  var HTMLHomePageElement: {
    prototype: HTMLHomePageElement;
    new (): HTMLHomePageElement;
  };

  interface HTMLSettingsPageElement extends Components.SettingsPage, HTMLStencilElement {}
  var HTMLSettingsPageElement: {
    prototype: HTMLSettingsPageElement;
    new (): HTMLSettingsPageElement;
  };

  interface HTMLElementTagNameMap {
    'site-root': HTMLSiteRootElement
    'home-page': HTMLHomePageElement
    'settings-page': HTMLSettingsPageElement
  }

  interface ElementTagNameMap {
    'site-root': HTMLSiteRootElement;
    'home-page': HTMLHomePageElement;
    'settings-page': HTMLSettingsPageElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
