/**
* This is an autogenerated file created by the Stencil compiler.
* It contains typing information for all components that exist in this project.
*/
/* tslint:disable */

import '@stencil/core';




export namespace Components {

  interface PlasticChat {
    'name': string;
  }
  interface PlasticChatAttributes extends StencilHTMLAttributes {
    'name'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'PlasticChat': Components.PlasticChat;
  }

  interface StencilIntrinsicElements {
    'plastic-chat': Components.PlasticChatAttributes;
  }


  interface HTMLPlasticChatElement extends Components.PlasticChat, HTMLStencilElement {}
  var HTMLPlasticChatElement: {
    prototype: HTMLPlasticChatElement;
    new (): HTMLPlasticChatElement;
  };

  interface HTMLElementTagNameMap {
    'plastic-chat': HTMLPlasticChatElement
  }

  interface ElementTagNameMap {
    'plastic-chat': HTMLPlasticChatElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
